// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Pointer<MyHandle> Function(ffi.Pointer<MyHandle>)>()
external ffi.Pointer<MyHandle> my_handle_clone(ffi.Pointer<MyHandle> h);

@ffi.Native<ffi.Pointer<MyHandle> Function()>()
external ffi.Pointer<MyHandle> my_handle_create();

@ffi.Native<ffi.Void Function(ffi.Pointer<MyHandle>)>()
external void my_handle_destroy(ffi.Pointer<MyHandle> h);

@ffi.Native<ffi.Pointer<OtherHandle> Function()>()
external ffi.Pointer<OtherHandle> other_handle_create();

final class MyHandle extends ffi.Opaque {}

final class OtherHandle extends ffi.Opaque {}
