// Copyright (c) 2023, the Dart project authors. Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

extension type const Options(int value) {
  static const Options none = Options(0);
  static const Options read = Options(1);
  static const Options write = Options(2);
  static const Options readWrite = Options(3);

  /// Whether this value contains all the bits set in [other].
  bool hasFlag(Options other) => (value & other.value) == other.value;

  /// Combines this value and [other] using bitwise-or.
  Options operator |(Options other) => Options(value | other.value);

  /// Intersects this value and [other] using bitwise-and.
  Options operator &(Options other) => Options(value & other.value);

  /// Exclusive-ors this value and [other].
  Options operator ^(Options other) => Options(value ^ other.value);

  /// The bitwise complement of this value.
  Options operator ~() => Options(~value);
}
